// Auto-generated file - do not edit manually
// Generated by scripts/generate-flag-imports.js

import flag_1_1_ad from './assets/flags/1x1/ad.svg';
import flag_1_1_ae from './assets/flags/1x1/ae.svg';
import flag_1_1_af from './assets/flags/1x1/af.svg';
import flag_1_1_ag from './assets/flags/1x1/ag.svg';
import flag_1_1_ai from './assets/flags/1x1/ai.svg';
import flag_1_1_al from './assets/flags/1x1/al.svg';
import flag_1_1_am from './assets/flags/1x1/am.svg';
import flag_1_1_ao from './assets/flags/1x1/ao.svg';
import flag_1_1_aq from './assets/flags/1x1/aq.svg';
import flag_1_1_ar from './assets/flags/1x1/ar.svg';
import flag_1_1_arab from './assets/flags/1x1/arab.svg';
import flag_1_1_as from './assets/flags/1x1/as.svg';
import flag_1_1_asean from './assets/flags/1x1/asean.svg';
import flag_1_1_at from './assets/flags/1x1/at.svg';
import flag_1_1_au from './assets/flags/1x1/au.svg';
import flag_1_1_aw from './assets/flags/1x1/aw.svg';
import flag_1_1_ax from './assets/flags/1x1/ax.svg';
import flag_1_1_az from './assets/flags/1x1/az.svg';
import flag_1_1_ba from './assets/flags/1x1/ba.svg';
import flag_1_1_bb from './assets/flags/1x1/bb.svg';
import flag_1_1_bd from './assets/flags/1x1/bd.svg';
import flag_1_1_be from './assets/flags/1x1/be.svg';
import flag_1_1_bf from './assets/flags/1x1/bf.svg';
import flag_1_1_bg from './assets/flags/1x1/bg.svg';
import flag_1_1_bh from './assets/flags/1x1/bh.svg';
import flag_1_1_bi from './assets/flags/1x1/bi.svg';
import flag_1_1_bj from './assets/flags/1x1/bj.svg';
import flag_1_1_bl from './assets/flags/1x1/bl.svg';
import flag_1_1_bm from './assets/flags/1x1/bm.svg';
import flag_1_1_bn from './assets/flags/1x1/bn.svg';
import flag_1_1_bo from './assets/flags/1x1/bo.svg';
import flag_1_1_bq from './assets/flags/1x1/bq.svg';
import flag_1_1_br from './assets/flags/1x1/br.svg';
import flag_1_1_bs from './assets/flags/1x1/bs.svg';
import flag_1_1_bt from './assets/flags/1x1/bt.svg';
import flag_1_1_bv from './assets/flags/1x1/bv.svg';
import flag_1_1_bw from './assets/flags/1x1/bw.svg';
import flag_1_1_by from './assets/flags/1x1/by.svg';
import flag_1_1_bz from './assets/flags/1x1/bz.svg';
import flag_1_1_ca from './assets/flags/1x1/ca.svg';
import flag_1_1_cc from './assets/flags/1x1/cc.svg';
import flag_1_1_cd from './assets/flags/1x1/cd.svg';
import flag_1_1_cefta from './assets/flags/1x1/cefta.svg';
import flag_1_1_cf from './assets/flags/1x1/cf.svg';
import flag_1_1_cg from './assets/flags/1x1/cg.svg';
import flag_1_1_ch from './assets/flags/1x1/ch.svg';
import flag_1_1_ci from './assets/flags/1x1/ci.svg';
import flag_1_1_ck from './assets/flags/1x1/ck.svg';
import flag_1_1_cl from './assets/flags/1x1/cl.svg';
import flag_1_1_cm from './assets/flags/1x1/cm.svg';
import flag_1_1_cn from './assets/flags/1x1/cn.svg';
import flag_1_1_co from './assets/flags/1x1/co.svg';
import flag_1_1_cp from './assets/flags/1x1/cp.svg';
import flag_1_1_cr from './assets/flags/1x1/cr.svg';
import flag_1_1_cu from './assets/flags/1x1/cu.svg';
import flag_1_1_cv from './assets/flags/1x1/cv.svg';
import flag_1_1_cw from './assets/flags/1x1/cw.svg';
import flag_1_1_cx from './assets/flags/1x1/cx.svg';
import flag_1_1_cy from './assets/flags/1x1/cy.svg';
import flag_1_1_cz from './assets/flags/1x1/cz.svg';
import flag_1_1_de from './assets/flags/1x1/de.svg';
import flag_1_1_dg from './assets/flags/1x1/dg.svg';
import flag_1_1_dj from './assets/flags/1x1/dj.svg';
import flag_1_1_dk from './assets/flags/1x1/dk.svg';
import flag_1_1_dm from './assets/flags/1x1/dm.svg';
import flag_1_1_do from './assets/flags/1x1/do.svg';
import flag_1_1_dz from './assets/flags/1x1/dz.svg';
import flag_1_1_eac from './assets/flags/1x1/eac.svg';
import flag_1_1_ec from './assets/flags/1x1/ec.svg';
import flag_1_1_ee from './assets/flags/1x1/ee.svg';
import flag_1_1_eg from './assets/flags/1x1/eg.svg';
import flag_1_1_eh from './assets/flags/1x1/eh.svg';
import flag_1_1_er from './assets/flags/1x1/er.svg';
import flag_1_1_es_ct from './assets/flags/1x1/es-ct.svg';
import flag_1_1_es_ga from './assets/flags/1x1/es-ga.svg';
import flag_1_1_es_pv from './assets/flags/1x1/es-pv.svg';
import flag_1_1_es from './assets/flags/1x1/es.svg';
import flag_1_1_et from './assets/flags/1x1/et.svg';
import flag_1_1_eu from './assets/flags/1x1/eu.svg';
import flag_1_1_fi from './assets/flags/1x1/fi.svg';
import flag_1_1_fj from './assets/flags/1x1/fj.svg';
import flag_1_1_fk from './assets/flags/1x1/fk.svg';
import flag_1_1_fm from './assets/flags/1x1/fm.svg';
import flag_1_1_fo from './assets/flags/1x1/fo.svg';
import flag_1_1_fr from './assets/flags/1x1/fr.svg';
import flag_1_1_ga from './assets/flags/1x1/ga.svg';
import flag_1_1_gb_eng from './assets/flags/1x1/gb-eng.svg';
import flag_1_1_gb_nir from './assets/flags/1x1/gb-nir.svg';
import flag_1_1_gb_sct from './assets/flags/1x1/gb-sct.svg';
import flag_1_1_gb_wls from './assets/flags/1x1/gb-wls.svg';
import flag_1_1_gb from './assets/flags/1x1/gb.svg';
import flag_1_1_gd from './assets/flags/1x1/gd.svg';
import flag_1_1_ge from './assets/flags/1x1/ge.svg';
import flag_1_1_gf from './assets/flags/1x1/gf.svg';
import flag_1_1_gg from './assets/flags/1x1/gg.svg';
import flag_1_1_gh from './assets/flags/1x1/gh.svg';
import flag_1_1_gi from './assets/flags/1x1/gi.svg';
import flag_1_1_gl from './assets/flags/1x1/gl.svg';
import flag_1_1_gm from './assets/flags/1x1/gm.svg';
import flag_1_1_gn from './assets/flags/1x1/gn.svg';
import flag_1_1_gp from './assets/flags/1x1/gp.svg';
import flag_1_1_gq from './assets/flags/1x1/gq.svg';
import flag_1_1_gr from './assets/flags/1x1/gr.svg';
import flag_1_1_gs from './assets/flags/1x1/gs.svg';
import flag_1_1_gt from './assets/flags/1x1/gt.svg';
import flag_1_1_gu from './assets/flags/1x1/gu.svg';
import flag_1_1_gw from './assets/flags/1x1/gw.svg';
import flag_1_1_gy from './assets/flags/1x1/gy.svg';
import flag_1_1_hk from './assets/flags/1x1/hk.svg';
import flag_1_1_hm from './assets/flags/1x1/hm.svg';
import flag_1_1_hn from './assets/flags/1x1/hn.svg';
import flag_1_1_hr from './assets/flags/1x1/hr.svg';
import flag_1_1_ht from './assets/flags/1x1/ht.svg';
import flag_1_1_hu from './assets/flags/1x1/hu.svg';
import flag_1_1_ic from './assets/flags/1x1/ic.svg';
import flag_1_1_id from './assets/flags/1x1/id.svg';
import flag_1_1_ie from './assets/flags/1x1/ie.svg';
import flag_1_1_il from './assets/flags/1x1/il.svg';
import flag_1_1_im from './assets/flags/1x1/im.svg';
import flag_1_1_in from './assets/flags/1x1/in.svg';
import flag_1_1_io from './assets/flags/1x1/io.svg';
import flag_1_1_iq from './assets/flags/1x1/iq.svg';
import flag_1_1_ir from './assets/flags/1x1/ir.svg';
import flag_1_1_is from './assets/flags/1x1/is.svg';
import flag_1_1_it from './assets/flags/1x1/it.svg';
import flag_1_1_je from './assets/flags/1x1/je.svg';
import flag_1_1_jm from './assets/flags/1x1/jm.svg';
import flag_1_1_jo from './assets/flags/1x1/jo.svg';
import flag_1_1_jp from './assets/flags/1x1/jp.svg';
import flag_1_1_ke from './assets/flags/1x1/ke.svg';
import flag_1_1_kg from './assets/flags/1x1/kg.svg';
import flag_1_1_kh from './assets/flags/1x1/kh.svg';
import flag_1_1_ki from './assets/flags/1x1/ki.svg';
import flag_1_1_km from './assets/flags/1x1/km.svg';
import flag_1_1_kn from './assets/flags/1x1/kn.svg';
import flag_1_1_kp from './assets/flags/1x1/kp.svg';
import flag_1_1_kr from './assets/flags/1x1/kr.svg';
import flag_1_1_kw from './assets/flags/1x1/kw.svg';
import flag_1_1_ky from './assets/flags/1x1/ky.svg';
import flag_1_1_kz from './assets/flags/1x1/kz.svg';
import flag_1_1_la from './assets/flags/1x1/la.svg';
import flag_1_1_lb from './assets/flags/1x1/lb.svg';
import flag_1_1_lc from './assets/flags/1x1/lc.svg';
import flag_1_1_li from './assets/flags/1x1/li.svg';
import flag_1_1_lk from './assets/flags/1x1/lk.svg';
import flag_1_1_lr from './assets/flags/1x1/lr.svg';
import flag_1_1_ls from './assets/flags/1x1/ls.svg';
import flag_1_1_lt from './assets/flags/1x1/lt.svg';
import flag_1_1_lu from './assets/flags/1x1/lu.svg';
import flag_1_1_lv from './assets/flags/1x1/lv.svg';
import flag_1_1_ly from './assets/flags/1x1/ly.svg';
import flag_1_1_ma from './assets/flags/1x1/ma.svg';
import flag_1_1_mc from './assets/flags/1x1/mc.svg';
import flag_1_1_md from './assets/flags/1x1/md.svg';
import flag_1_1_me from './assets/flags/1x1/me.svg';
import flag_1_1_mf from './assets/flags/1x1/mf.svg';
import flag_1_1_mg from './assets/flags/1x1/mg.svg';
import flag_1_1_mh from './assets/flags/1x1/mh.svg';
import flag_1_1_mk from './assets/flags/1x1/mk.svg';
import flag_1_1_ml from './assets/flags/1x1/ml.svg';
import flag_1_1_mm from './assets/flags/1x1/mm.svg';
import flag_1_1_mn from './assets/flags/1x1/mn.svg';
import flag_1_1_mo from './assets/flags/1x1/mo.svg';
import flag_1_1_mp from './assets/flags/1x1/mp.svg';
import flag_1_1_mq from './assets/flags/1x1/mq.svg';
import flag_1_1_mr from './assets/flags/1x1/mr.svg';
import flag_1_1_ms from './assets/flags/1x1/ms.svg';
import flag_1_1_mt from './assets/flags/1x1/mt.svg';
import flag_1_1_mu from './assets/flags/1x1/mu.svg';
import flag_1_1_mv from './assets/flags/1x1/mv.svg';
import flag_1_1_mw from './assets/flags/1x1/mw.svg';
import flag_1_1_mx from './assets/flags/1x1/mx.svg';
import flag_1_1_my from './assets/flags/1x1/my.svg';
import flag_1_1_mz from './assets/flags/1x1/mz.svg';
import flag_1_1_na from './assets/flags/1x1/na.svg';
import flag_1_1_nc from './assets/flags/1x1/nc.svg';
import flag_1_1_ne from './assets/flags/1x1/ne.svg';
import flag_1_1_nf from './assets/flags/1x1/nf.svg';
import flag_1_1_ng from './assets/flags/1x1/ng.svg';
import flag_1_1_ni from './assets/flags/1x1/ni.svg';
import flag_1_1_nl from './assets/flags/1x1/nl.svg';
import flag_1_1_no from './assets/flags/1x1/no.svg';
import flag_1_1_np from './assets/flags/1x1/np.svg';
import flag_1_1_nr from './assets/flags/1x1/nr.svg';
import flag_1_1_nu from './assets/flags/1x1/nu.svg';
import flag_1_1_nz from './assets/flags/1x1/nz.svg';
import flag_1_1_om from './assets/flags/1x1/om.svg';
import flag_1_1_pa from './assets/flags/1x1/pa.svg';
import flag_1_1_pc from './assets/flags/1x1/pc.svg';
import flag_1_1_pe from './assets/flags/1x1/pe.svg';
import flag_1_1_pf from './assets/flags/1x1/pf.svg';
import flag_1_1_pg from './assets/flags/1x1/pg.svg';
import flag_1_1_ph from './assets/flags/1x1/ph.svg';
import flag_1_1_pk from './assets/flags/1x1/pk.svg';
import flag_1_1_pl from './assets/flags/1x1/pl.svg';
import flag_1_1_pm from './assets/flags/1x1/pm.svg';
import flag_1_1_pn from './assets/flags/1x1/pn.svg';
import flag_1_1_pr from './assets/flags/1x1/pr.svg';
import flag_1_1_ps from './assets/flags/1x1/ps.svg';
import flag_1_1_pt from './assets/flags/1x1/pt.svg';
import flag_1_1_pw from './assets/flags/1x1/pw.svg';
import flag_1_1_py from './assets/flags/1x1/py.svg';
import flag_1_1_qa from './assets/flags/1x1/qa.svg';
import flag_1_1_re from './assets/flags/1x1/re.svg';
import flag_1_1_ro from './assets/flags/1x1/ro.svg';
import flag_1_1_rs from './assets/flags/1x1/rs.svg';
import flag_1_1_ru from './assets/flags/1x1/ru.svg';
import flag_1_1_rw from './assets/flags/1x1/rw.svg';
import flag_1_1_sa from './assets/flags/1x1/sa.svg';
import flag_1_1_sb from './assets/flags/1x1/sb.svg';
import flag_1_1_sc from './assets/flags/1x1/sc.svg';
import flag_1_1_sd from './assets/flags/1x1/sd.svg';
import flag_1_1_se from './assets/flags/1x1/se.svg';
import flag_1_1_sg from './assets/flags/1x1/sg.svg';
import flag_1_1_sh_ac from './assets/flags/1x1/sh-ac.svg';
import flag_1_1_sh_hl from './assets/flags/1x1/sh-hl.svg';
import flag_1_1_sh_ta from './assets/flags/1x1/sh-ta.svg';
import flag_1_1_sh from './assets/flags/1x1/sh.svg';
import flag_1_1_si from './assets/flags/1x1/si.svg';
import flag_1_1_sj from './assets/flags/1x1/sj.svg';
import flag_1_1_sk from './assets/flags/1x1/sk.svg';
import flag_1_1_sl from './assets/flags/1x1/sl.svg';
import flag_1_1_sm from './assets/flags/1x1/sm.svg';
import flag_1_1_sn from './assets/flags/1x1/sn.svg';
import flag_1_1_so from './assets/flags/1x1/so.svg';
import flag_1_1_sr from './assets/flags/1x1/sr.svg';
import flag_1_1_ss from './assets/flags/1x1/ss.svg';
import flag_1_1_st from './assets/flags/1x1/st.svg';
import flag_1_1_sv from './assets/flags/1x1/sv.svg';
import flag_1_1_sx from './assets/flags/1x1/sx.svg';
import flag_1_1_sy from './assets/flags/1x1/sy.svg';
import flag_1_1_sz from './assets/flags/1x1/sz.svg';
import flag_1_1_tc from './assets/flags/1x1/tc.svg';
import flag_1_1_td from './assets/flags/1x1/td.svg';
import flag_1_1_tf from './assets/flags/1x1/tf.svg';
import flag_1_1_tg from './assets/flags/1x1/tg.svg';
import flag_1_1_th from './assets/flags/1x1/th.svg';
import flag_1_1_tj from './assets/flags/1x1/tj.svg';
import flag_1_1_tk from './assets/flags/1x1/tk.svg';
import flag_1_1_tl from './assets/flags/1x1/tl.svg';
import flag_1_1_tm from './assets/flags/1x1/tm.svg';
import flag_1_1_tn from './assets/flags/1x1/tn.svg';
import flag_1_1_to from './assets/flags/1x1/to.svg';
import flag_1_1_tr from './assets/flags/1x1/tr.svg';
import flag_1_1_tt from './assets/flags/1x1/tt.svg';
import flag_1_1_tv from './assets/flags/1x1/tv.svg';
import flag_1_1_tw from './assets/flags/1x1/tw.svg';
import flag_1_1_tz from './assets/flags/1x1/tz.svg';
import flag_1_1_ua from './assets/flags/1x1/ua.svg';
import flag_1_1_ug from './assets/flags/1x1/ug.svg';
import flag_1_1_um from './assets/flags/1x1/um.svg';
import flag_1_1_un from './assets/flags/1x1/un.svg';
import flag_1_1_us from './assets/flags/1x1/us.svg';
import flag_1_1_uy from './assets/flags/1x1/uy.svg';
import flag_1_1_uz from './assets/flags/1x1/uz.svg';
import flag_1_1_va from './assets/flags/1x1/va.svg';
import flag_1_1_vc from './assets/flags/1x1/vc.svg';
import flag_1_1_ve from './assets/flags/1x1/ve.svg';
import flag_1_1_vg from './assets/flags/1x1/vg.svg';
import flag_1_1_vi from './assets/flags/1x1/vi.svg';
import flag_1_1_vn from './assets/flags/1x1/vn.svg';
import flag_1_1_vu from './assets/flags/1x1/vu.svg';
import flag_1_1_wf from './assets/flags/1x1/wf.svg';
import flag_1_1_ws from './assets/flags/1x1/ws.svg';
import flag_1_1_xk from './assets/flags/1x1/xk.svg';
import flag_1_1_xx from './assets/flags/1x1/xx.svg';
import flag_1_1_ye from './assets/flags/1x1/ye.svg';
import flag_1_1_yt from './assets/flags/1x1/yt.svg';
import flag_1_1_za from './assets/flags/1x1/za.svg';
import flag_1_1_zm from './assets/flags/1x1/zm.svg';
import flag_1_1_zw from './assets/flags/1x1/zw.svg';
import flag_4_3_ad from './assets/flags/4x3/ad.svg';
import flag_4_3_ae from './assets/flags/4x3/ae.svg';
import flag_4_3_af from './assets/flags/4x3/af.svg';
import flag_4_3_ag from './assets/flags/4x3/ag.svg';
import flag_4_3_ai from './assets/flags/4x3/ai.svg';
import flag_4_3_al from './assets/flags/4x3/al.svg';
import flag_4_3_am from './assets/flags/4x3/am.svg';
import flag_4_3_ao from './assets/flags/4x3/ao.svg';
import flag_4_3_aq from './assets/flags/4x3/aq.svg';
import flag_4_3_ar from './assets/flags/4x3/ar.svg';
import flag_4_3_arab from './assets/flags/4x3/arab.svg';
import flag_4_3_as from './assets/flags/4x3/as.svg';
import flag_4_3_asean from './assets/flags/4x3/asean.svg';
import flag_4_3_at from './assets/flags/4x3/at.svg';
import flag_4_3_au from './assets/flags/4x3/au.svg';
import flag_4_3_aw from './assets/flags/4x3/aw.svg';
import flag_4_3_ax from './assets/flags/4x3/ax.svg';
import flag_4_3_az from './assets/flags/4x3/az.svg';
import flag_4_3_ba from './assets/flags/4x3/ba.svg';
import flag_4_3_bb from './assets/flags/4x3/bb.svg';
import flag_4_3_bd from './assets/flags/4x3/bd.svg';
import flag_4_3_be from './assets/flags/4x3/be.svg';
import flag_4_3_bf from './assets/flags/4x3/bf.svg';
import flag_4_3_bg from './assets/flags/4x3/bg.svg';
import flag_4_3_bh from './assets/flags/4x3/bh.svg';
import flag_4_3_bi from './assets/flags/4x3/bi.svg';
import flag_4_3_bj from './assets/flags/4x3/bj.svg';
import flag_4_3_bl from './assets/flags/4x3/bl.svg';
import flag_4_3_bm from './assets/flags/4x3/bm.svg';
import flag_4_3_bn from './assets/flags/4x3/bn.svg';
import flag_4_3_bo from './assets/flags/4x3/bo.svg';
import flag_4_3_bq from './assets/flags/4x3/bq.svg';
import flag_4_3_br from './assets/flags/4x3/br.svg';
import flag_4_3_bs from './assets/flags/4x3/bs.svg';
import flag_4_3_bt from './assets/flags/4x3/bt.svg';
import flag_4_3_bv from './assets/flags/4x3/bv.svg';
import flag_4_3_bw from './assets/flags/4x3/bw.svg';
import flag_4_3_by from './assets/flags/4x3/by.svg';
import flag_4_3_bz from './assets/flags/4x3/bz.svg';
import flag_4_3_ca from './assets/flags/4x3/ca.svg';
import flag_4_3_cc from './assets/flags/4x3/cc.svg';
import flag_4_3_cd from './assets/flags/4x3/cd.svg';
import flag_4_3_cefta from './assets/flags/4x3/cefta.svg';
import flag_4_3_cf from './assets/flags/4x3/cf.svg';
import flag_4_3_cg from './assets/flags/4x3/cg.svg';
import flag_4_3_ch from './assets/flags/4x3/ch.svg';
import flag_4_3_ci from './assets/flags/4x3/ci.svg';
import flag_4_3_ck from './assets/flags/4x3/ck.svg';
import flag_4_3_cl from './assets/flags/4x3/cl.svg';
import flag_4_3_cm from './assets/flags/4x3/cm.svg';
import flag_4_3_cn from './assets/flags/4x3/cn.svg';
import flag_4_3_co from './assets/flags/4x3/co.svg';
import flag_4_3_cp from './assets/flags/4x3/cp.svg';
import flag_4_3_cr from './assets/flags/4x3/cr.svg';
import flag_4_3_cu from './assets/flags/4x3/cu.svg';
import flag_4_3_cv from './assets/flags/4x3/cv.svg';
import flag_4_3_cw from './assets/flags/4x3/cw.svg';
import flag_4_3_cx from './assets/flags/4x3/cx.svg';
import flag_4_3_cy from './assets/flags/4x3/cy.svg';
import flag_4_3_cz from './assets/flags/4x3/cz.svg';
import flag_4_3_de from './assets/flags/4x3/de.svg';
import flag_4_3_dg from './assets/flags/4x3/dg.svg';
import flag_4_3_dj from './assets/flags/4x3/dj.svg';
import flag_4_3_dk from './assets/flags/4x3/dk.svg';
import flag_4_3_dm from './assets/flags/4x3/dm.svg';
import flag_4_3_do from './assets/flags/4x3/do.svg';
import flag_4_3_dz from './assets/flags/4x3/dz.svg';
import flag_4_3_eac from './assets/flags/4x3/eac.svg';
import flag_4_3_ec from './assets/flags/4x3/ec.svg';
import flag_4_3_ee from './assets/flags/4x3/ee.svg';
import flag_4_3_eg from './assets/flags/4x3/eg.svg';
import flag_4_3_eh from './assets/flags/4x3/eh.svg';
import flag_4_3_er from './assets/flags/4x3/er.svg';
import flag_4_3_es_ct from './assets/flags/4x3/es-ct.svg';
import flag_4_3_es_ga from './assets/flags/4x3/es-ga.svg';
import flag_4_3_es_pv from './assets/flags/4x3/es-pv.svg';
import flag_4_3_es from './assets/flags/4x3/es.svg';
import flag_4_3_et from './assets/flags/4x3/et.svg';
import flag_4_3_eu from './assets/flags/4x3/eu.svg';
import flag_4_3_fi from './assets/flags/4x3/fi.svg';
import flag_4_3_fj from './assets/flags/4x3/fj.svg';
import flag_4_3_fk from './assets/flags/4x3/fk.svg';
import flag_4_3_fm from './assets/flags/4x3/fm.svg';
import flag_4_3_fo from './assets/flags/4x3/fo.svg';
import flag_4_3_fr from './assets/flags/4x3/fr.svg';
import flag_4_3_ga from './assets/flags/4x3/ga.svg';
import flag_4_3_gb_eng from './assets/flags/4x3/gb-eng.svg';
import flag_4_3_gb_nir from './assets/flags/4x3/gb-nir.svg';
import flag_4_3_gb_sct from './assets/flags/4x3/gb-sct.svg';
import flag_4_3_gb_wls from './assets/flags/4x3/gb-wls.svg';
import flag_4_3_gb from './assets/flags/4x3/gb.svg';
import flag_4_3_gd from './assets/flags/4x3/gd.svg';
import flag_4_3_ge from './assets/flags/4x3/ge.svg';
import flag_4_3_gf from './assets/flags/4x3/gf.svg';
import flag_4_3_gg from './assets/flags/4x3/gg.svg';
import flag_4_3_gh from './assets/flags/4x3/gh.svg';
import flag_4_3_gi from './assets/flags/4x3/gi.svg';
import flag_4_3_gl from './assets/flags/4x3/gl.svg';
import flag_4_3_gm from './assets/flags/4x3/gm.svg';
import flag_4_3_gn from './assets/flags/4x3/gn.svg';
import flag_4_3_gp from './assets/flags/4x3/gp.svg';
import flag_4_3_gq from './assets/flags/4x3/gq.svg';
import flag_4_3_gr from './assets/flags/4x3/gr.svg';
import flag_4_3_gs from './assets/flags/4x3/gs.svg';
import flag_4_3_gt from './assets/flags/4x3/gt.svg';
import flag_4_3_gu from './assets/flags/4x3/gu.svg';
import flag_4_3_gw from './assets/flags/4x3/gw.svg';
import flag_4_3_gy from './assets/flags/4x3/gy.svg';
import flag_4_3_hk from './assets/flags/4x3/hk.svg';
import flag_4_3_hm from './assets/flags/4x3/hm.svg';
import flag_4_3_hn from './assets/flags/4x3/hn.svg';
import flag_4_3_hr from './assets/flags/4x3/hr.svg';
import flag_4_3_ht from './assets/flags/4x3/ht.svg';
import flag_4_3_hu from './assets/flags/4x3/hu.svg';
import flag_4_3_ic from './assets/flags/4x3/ic.svg';
import flag_4_3_id from './assets/flags/4x3/id.svg';
import flag_4_3_ie from './assets/flags/4x3/ie.svg';
import flag_4_3_il from './assets/flags/4x3/il.svg';
import flag_4_3_im from './assets/flags/4x3/im.svg';
import flag_4_3_in from './assets/flags/4x3/in.svg';
import flag_4_3_io from './assets/flags/4x3/io.svg';
import flag_4_3_iq from './assets/flags/4x3/iq.svg';
import flag_4_3_ir from './assets/flags/4x3/ir.svg';
import flag_4_3_is from './assets/flags/4x3/is.svg';
import flag_4_3_it from './assets/flags/4x3/it.svg';
import flag_4_3_je from './assets/flags/4x3/je.svg';
import flag_4_3_jm from './assets/flags/4x3/jm.svg';
import flag_4_3_jo from './assets/flags/4x3/jo.svg';
import flag_4_3_jp from './assets/flags/4x3/jp.svg';
import flag_4_3_ke from './assets/flags/4x3/ke.svg';
import flag_4_3_kg from './assets/flags/4x3/kg.svg';
import flag_4_3_kh from './assets/flags/4x3/kh.svg';
import flag_4_3_ki from './assets/flags/4x3/ki.svg';
import flag_4_3_km from './assets/flags/4x3/km.svg';
import flag_4_3_kn from './assets/flags/4x3/kn.svg';
import flag_4_3_kp from './assets/flags/4x3/kp.svg';
import flag_4_3_kr from './assets/flags/4x3/kr.svg';
import flag_4_3_kw from './assets/flags/4x3/kw.svg';
import flag_4_3_ky from './assets/flags/4x3/ky.svg';
import flag_4_3_kz from './assets/flags/4x3/kz.svg';
import flag_4_3_la from './assets/flags/4x3/la.svg';
import flag_4_3_lb from './assets/flags/4x3/lb.svg';
import flag_4_3_lc from './assets/flags/4x3/lc.svg';
import flag_4_3_li from './assets/flags/4x3/li.svg';
import flag_4_3_lk from './assets/flags/4x3/lk.svg';
import flag_4_3_lr from './assets/flags/4x3/lr.svg';
import flag_4_3_ls from './assets/flags/4x3/ls.svg';
import flag_4_3_lt from './assets/flags/4x3/lt.svg';
import flag_4_3_lu from './assets/flags/4x3/lu.svg';
import flag_4_3_lv from './assets/flags/4x3/lv.svg';
import flag_4_3_ly from './assets/flags/4x3/ly.svg';
import flag_4_3_ma from './assets/flags/4x3/ma.svg';
import flag_4_3_mc from './assets/flags/4x3/mc.svg';
import flag_4_3_md from './assets/flags/4x3/md.svg';
import flag_4_3_me from './assets/flags/4x3/me.svg';
import flag_4_3_mf from './assets/flags/4x3/mf.svg';
import flag_4_3_mg from './assets/flags/4x3/mg.svg';
import flag_4_3_mh from './assets/flags/4x3/mh.svg';
import flag_4_3_mk from './assets/flags/4x3/mk.svg';
import flag_4_3_ml from './assets/flags/4x3/ml.svg';
import flag_4_3_mm from './assets/flags/4x3/mm.svg';
import flag_4_3_mn from './assets/flags/4x3/mn.svg';
import flag_4_3_mo from './assets/flags/4x3/mo.svg';
import flag_4_3_mp from './assets/flags/4x3/mp.svg';
import flag_4_3_mq from './assets/flags/4x3/mq.svg';
import flag_4_3_mr from './assets/flags/4x3/mr.svg';
import flag_4_3_ms from './assets/flags/4x3/ms.svg';
import flag_4_3_mt from './assets/flags/4x3/mt.svg';
import flag_4_3_mu from './assets/flags/4x3/mu.svg';
import flag_4_3_mv from './assets/flags/4x3/mv.svg';
import flag_4_3_mw from './assets/flags/4x3/mw.svg';
import flag_4_3_mx from './assets/flags/4x3/mx.svg';
import flag_4_3_my from './assets/flags/4x3/my.svg';
import flag_4_3_mz from './assets/flags/4x3/mz.svg';
import flag_4_3_na from './assets/flags/4x3/na.svg';
import flag_4_3_nc from './assets/flags/4x3/nc.svg';
import flag_4_3_ne from './assets/flags/4x3/ne.svg';
import flag_4_3_nf from './assets/flags/4x3/nf.svg';
import flag_4_3_ng from './assets/flags/4x3/ng.svg';
import flag_4_3_ni from './assets/flags/4x3/ni.svg';
import flag_4_3_nl from './assets/flags/4x3/nl.svg';
import flag_4_3_no from './assets/flags/4x3/no.svg';
import flag_4_3_np from './assets/flags/4x3/np.svg';
import flag_4_3_nr from './assets/flags/4x3/nr.svg';
import flag_4_3_nu from './assets/flags/4x3/nu.svg';
import flag_4_3_nz from './assets/flags/4x3/nz.svg';
import flag_4_3_om from './assets/flags/4x3/om.svg';
import flag_4_3_pa from './assets/flags/4x3/pa.svg';
import flag_4_3_pc from './assets/flags/4x3/pc.svg';
import flag_4_3_pe from './assets/flags/4x3/pe.svg';
import flag_4_3_pf from './assets/flags/4x3/pf.svg';
import flag_4_3_pg from './assets/flags/4x3/pg.svg';
import flag_4_3_ph from './assets/flags/4x3/ph.svg';
import flag_4_3_pk from './assets/flags/4x3/pk.svg';
import flag_4_3_pl from './assets/flags/4x3/pl.svg';
import flag_4_3_pm from './assets/flags/4x3/pm.svg';
import flag_4_3_pn from './assets/flags/4x3/pn.svg';
import flag_4_3_pr from './assets/flags/4x3/pr.svg';
import flag_4_3_ps from './assets/flags/4x3/ps.svg';
import flag_4_3_pt from './assets/flags/4x3/pt.svg';
import flag_4_3_pw from './assets/flags/4x3/pw.svg';
import flag_4_3_py from './assets/flags/4x3/py.svg';
import flag_4_3_qa from './assets/flags/4x3/qa.svg';
import flag_4_3_re from './assets/flags/4x3/re.svg';
import flag_4_3_ro from './assets/flags/4x3/ro.svg';
import flag_4_3_rs from './assets/flags/4x3/rs.svg';
import flag_4_3_ru from './assets/flags/4x3/ru.svg';
import flag_4_3_rw from './assets/flags/4x3/rw.svg';
import flag_4_3_sa from './assets/flags/4x3/sa.svg';
import flag_4_3_sb from './assets/flags/4x3/sb.svg';
import flag_4_3_sc from './assets/flags/4x3/sc.svg';
import flag_4_3_sd from './assets/flags/4x3/sd.svg';
import flag_4_3_se from './assets/flags/4x3/se.svg';
import flag_4_3_sg from './assets/flags/4x3/sg.svg';
import flag_4_3_sh_ac from './assets/flags/4x3/sh-ac.svg';
import flag_4_3_sh_hl from './assets/flags/4x3/sh-hl.svg';
import flag_4_3_sh_ta from './assets/flags/4x3/sh-ta.svg';
import flag_4_3_sh from './assets/flags/4x3/sh.svg';
import flag_4_3_si from './assets/flags/4x3/si.svg';
import flag_4_3_sj from './assets/flags/4x3/sj.svg';
import flag_4_3_sk from './assets/flags/4x3/sk.svg';
import flag_4_3_sl from './assets/flags/4x3/sl.svg';
import flag_4_3_sm from './assets/flags/4x3/sm.svg';
import flag_4_3_sn from './assets/flags/4x3/sn.svg';
import flag_4_3_so from './assets/flags/4x3/so.svg';
import flag_4_3_sr from './assets/flags/4x3/sr.svg';
import flag_4_3_ss from './assets/flags/4x3/ss.svg';
import flag_4_3_st from './assets/flags/4x3/st.svg';
import flag_4_3_sv from './assets/flags/4x3/sv.svg';
import flag_4_3_sx from './assets/flags/4x3/sx.svg';
import flag_4_3_sy from './assets/flags/4x3/sy.svg';
import flag_4_3_sz from './assets/flags/4x3/sz.svg';
import flag_4_3_tc from './assets/flags/4x3/tc.svg';
import flag_4_3_td from './assets/flags/4x3/td.svg';
import flag_4_3_tf from './assets/flags/4x3/tf.svg';
import flag_4_3_tg from './assets/flags/4x3/tg.svg';
import flag_4_3_th from './assets/flags/4x3/th.svg';
import flag_4_3_tj from './assets/flags/4x3/tj.svg';
import flag_4_3_tk from './assets/flags/4x3/tk.svg';
import flag_4_3_tl from './assets/flags/4x3/tl.svg';
import flag_4_3_tm from './assets/flags/4x3/tm.svg';
import flag_4_3_tn from './assets/flags/4x3/tn.svg';
import flag_4_3_to from './assets/flags/4x3/to.svg';
import flag_4_3_tr from './assets/flags/4x3/tr.svg';
import flag_4_3_tt from './assets/flags/4x3/tt.svg';
import flag_4_3_tv from './assets/flags/4x3/tv.svg';
import flag_4_3_tw from './assets/flags/4x3/tw.svg';
import flag_4_3_tz from './assets/flags/4x3/tz.svg';
import flag_4_3_ua from './assets/flags/4x3/ua.svg';
import flag_4_3_ug from './assets/flags/4x3/ug.svg';
import flag_4_3_um from './assets/flags/4x3/um.svg';
import flag_4_3_un from './assets/flags/4x3/un.svg';
import flag_4_3_us from './assets/flags/4x3/us.svg';
import flag_4_3_uy from './assets/flags/4x3/uy.svg';
import flag_4_3_uz from './assets/flags/4x3/uz.svg';
import flag_4_3_va from './assets/flags/4x3/va.svg';
import flag_4_3_vc from './assets/flags/4x3/vc.svg';
import flag_4_3_ve from './assets/flags/4x3/ve.svg';
import flag_4_3_vg from './assets/flags/4x3/vg.svg';
import flag_4_3_vi from './assets/flags/4x3/vi.svg';
import flag_4_3_vn from './assets/flags/4x3/vn.svg';
import flag_4_3_vu from './assets/flags/4x3/vu.svg';
import flag_4_3_wf from './assets/flags/4x3/wf.svg';
import flag_4_3_ws from './assets/flags/4x3/ws.svg';
import flag_4_3_xk from './assets/flags/4x3/xk.svg';
import flag_4_3_xx from './assets/flags/4x3/xx.svg';
import flag_4_3_ye from './assets/flags/4x3/ye.svg';
import flag_4_3_yt from './assets/flags/4x3/yt.svg';
import flag_4_3_za from './assets/flags/4x3/za.svg';
import flag_4_3_zm from './assets/flags/4x3/zm.svg';
import flag_4_3_zw from './assets/flags/4x3/zw.svg';

export const flags1x1: Record<string, string> = {
  'ad': flag_1_1_ad,
  'ae': flag_1_1_ae,
  'af': flag_1_1_af,
  'ag': flag_1_1_ag,
  'ai': flag_1_1_ai,
  'al': flag_1_1_al,
  'am': flag_1_1_am,
  'ao': flag_1_1_ao,
  'aq': flag_1_1_aq,
  'ar': flag_1_1_ar,
  'arab': flag_1_1_arab,
  'as': flag_1_1_as,
  'asean': flag_1_1_asean,
  'at': flag_1_1_at,
  'au': flag_1_1_au,
  'aw': flag_1_1_aw,
  'ax': flag_1_1_ax,
  'az': flag_1_1_az,
  'ba': flag_1_1_ba,
  'bb': flag_1_1_bb,
  'bd': flag_1_1_bd,
  'be': flag_1_1_be,
  'bf': flag_1_1_bf,
  'bg': flag_1_1_bg,
  'bh': flag_1_1_bh,
  'bi': flag_1_1_bi,
  'bj': flag_1_1_bj,
  'bl': flag_1_1_bl,
  'bm': flag_1_1_bm,
  'bn': flag_1_1_bn,
  'bo': flag_1_1_bo,
  'bq': flag_1_1_bq,
  'br': flag_1_1_br,
  'bs': flag_1_1_bs,
  'bt': flag_1_1_bt,
  'bv': flag_1_1_bv,
  'bw': flag_1_1_bw,
  'by': flag_1_1_by,
  'bz': flag_1_1_bz,
  'ca': flag_1_1_ca,
  'cc': flag_1_1_cc,
  'cd': flag_1_1_cd,
  'cefta': flag_1_1_cefta,
  'cf': flag_1_1_cf,
  'cg': flag_1_1_cg,
  'ch': flag_1_1_ch,
  'ci': flag_1_1_ci,
  'ck': flag_1_1_ck,
  'cl': flag_1_1_cl,
  'cm': flag_1_1_cm,
  'cn': flag_1_1_cn,
  'co': flag_1_1_co,
  'cp': flag_1_1_cp,
  'cr': flag_1_1_cr,
  'cu': flag_1_1_cu,
  'cv': flag_1_1_cv,
  'cw': flag_1_1_cw,
  'cx': flag_1_1_cx,
  'cy': flag_1_1_cy,
  'cz': flag_1_1_cz,
  'de': flag_1_1_de,
  'dg': flag_1_1_dg,
  'dj': flag_1_1_dj,
  'dk': flag_1_1_dk,
  'dm': flag_1_1_dm,
  'do': flag_1_1_do,
  'dz': flag_1_1_dz,
  'eac': flag_1_1_eac,
  'ec': flag_1_1_ec,
  'ee': flag_1_1_ee,
  'eg': flag_1_1_eg,
  'eh': flag_1_1_eh,
  'er': flag_1_1_er,
  'es-ct': flag_1_1_es_ct,
  'es-ga': flag_1_1_es_ga,
  'es-pv': flag_1_1_es_pv,
  'es': flag_1_1_es,
  'et': flag_1_1_et,
  'eu': flag_1_1_eu,
  'fi': flag_1_1_fi,
  'fj': flag_1_1_fj,
  'fk': flag_1_1_fk,
  'fm': flag_1_1_fm,
  'fo': flag_1_1_fo,
  'fr': flag_1_1_fr,
  'ga': flag_1_1_ga,
  'gb-eng': flag_1_1_gb_eng,
  'gb-nir': flag_1_1_gb_nir,
  'gb-sct': flag_1_1_gb_sct,
  'gb-wls': flag_1_1_gb_wls,
  'gb': flag_1_1_gb,
  'gd': flag_1_1_gd,
  'ge': flag_1_1_ge,
  'gf': flag_1_1_gf,
  'gg': flag_1_1_gg,
  'gh': flag_1_1_gh,
  'gi': flag_1_1_gi,
  'gl': flag_1_1_gl,
  'gm': flag_1_1_gm,
  'gn': flag_1_1_gn,
  'gp': flag_1_1_gp,
  'gq': flag_1_1_gq,
  'gr': flag_1_1_gr,
  'gs': flag_1_1_gs,
  'gt': flag_1_1_gt,
  'gu': flag_1_1_gu,
  'gw': flag_1_1_gw,
  'gy': flag_1_1_gy,
  'hk': flag_1_1_hk,
  'hm': flag_1_1_hm,
  'hn': flag_1_1_hn,
  'hr': flag_1_1_hr,
  'ht': flag_1_1_ht,
  'hu': flag_1_1_hu,
  'ic': flag_1_1_ic,
  'id': flag_1_1_id,
  'ie': flag_1_1_ie,
  'il': flag_1_1_il,
  'im': flag_1_1_im,
  'in': flag_1_1_in,
  'io': flag_1_1_io,
  'iq': flag_1_1_iq,
  'ir': flag_1_1_ir,
  'is': flag_1_1_is,
  'it': flag_1_1_it,
  'je': flag_1_1_je,
  'jm': flag_1_1_jm,
  'jo': flag_1_1_jo,
  'jp': flag_1_1_jp,
  'ke': flag_1_1_ke,
  'kg': flag_1_1_kg,
  'kh': flag_1_1_kh,
  'ki': flag_1_1_ki,
  'km': flag_1_1_km,
  'kn': flag_1_1_kn,
  'kp': flag_1_1_kp,
  'kr': flag_1_1_kr,
  'kw': flag_1_1_kw,
  'ky': flag_1_1_ky,
  'kz': flag_1_1_kz,
  'la': flag_1_1_la,
  'lb': flag_1_1_lb,
  'lc': flag_1_1_lc,
  'li': flag_1_1_li,
  'lk': flag_1_1_lk,
  'lr': flag_1_1_lr,
  'ls': flag_1_1_ls,
  'lt': flag_1_1_lt,
  'lu': flag_1_1_lu,
  'lv': flag_1_1_lv,
  'ly': flag_1_1_ly,
  'ma': flag_1_1_ma,
  'mc': flag_1_1_mc,
  'md': flag_1_1_md,
  'me': flag_1_1_me,
  'mf': flag_1_1_mf,
  'mg': flag_1_1_mg,
  'mh': flag_1_1_mh,
  'mk': flag_1_1_mk,
  'ml': flag_1_1_ml,
  'mm': flag_1_1_mm,
  'mn': flag_1_1_mn,
  'mo': flag_1_1_mo,
  'mp': flag_1_1_mp,
  'mq': flag_1_1_mq,
  'mr': flag_1_1_mr,
  'ms': flag_1_1_ms,
  'mt': flag_1_1_mt,
  'mu': flag_1_1_mu,
  'mv': flag_1_1_mv,
  'mw': flag_1_1_mw,
  'mx': flag_1_1_mx,
  'my': flag_1_1_my,
  'mz': flag_1_1_mz,
  'na': flag_1_1_na,
  'nc': flag_1_1_nc,
  'ne': flag_1_1_ne,
  'nf': flag_1_1_nf,
  'ng': flag_1_1_ng,
  'ni': flag_1_1_ni,
  'nl': flag_1_1_nl,
  'no': flag_1_1_no,
  'np': flag_1_1_np,
  'nr': flag_1_1_nr,
  'nu': flag_1_1_nu,
  'nz': flag_1_1_nz,
  'om': flag_1_1_om,
  'pa': flag_1_1_pa,
  'pc': flag_1_1_pc,
  'pe': flag_1_1_pe,
  'pf': flag_1_1_pf,
  'pg': flag_1_1_pg,
  'ph': flag_1_1_ph,
  'pk': flag_1_1_pk,
  'pl': flag_1_1_pl,
  'pm': flag_1_1_pm,
  'pn': flag_1_1_pn,
  'pr': flag_1_1_pr,
  'ps': flag_1_1_ps,
  'pt': flag_1_1_pt,
  'pw': flag_1_1_pw,
  'py': flag_1_1_py,
  'qa': flag_1_1_qa,
  're': flag_1_1_re,
  'ro': flag_1_1_ro,
  'rs': flag_1_1_rs,
  'ru': flag_1_1_ru,
  'rw': flag_1_1_rw,
  'sa': flag_1_1_sa,
  'sb': flag_1_1_sb,
  'sc': flag_1_1_sc,
  'sd': flag_1_1_sd,
  'se': flag_1_1_se,
  'sg': flag_1_1_sg,
  'sh-ac': flag_1_1_sh_ac,
  'sh-hl': flag_1_1_sh_hl,
  'sh-ta': flag_1_1_sh_ta,
  'sh': flag_1_1_sh,
  'si': flag_1_1_si,
  'sj': flag_1_1_sj,
  'sk': flag_1_1_sk,
  'sl': flag_1_1_sl,
  'sm': flag_1_1_sm,
  'sn': flag_1_1_sn,
  'so': flag_1_1_so,
  'sr': flag_1_1_sr,
  'ss': flag_1_1_ss,
  'st': flag_1_1_st,
  'sv': flag_1_1_sv,
  'sx': flag_1_1_sx,
  'sy': flag_1_1_sy,
  'sz': flag_1_1_sz,
  'tc': flag_1_1_tc,
  'td': flag_1_1_td,
  'tf': flag_1_1_tf,
  'tg': flag_1_1_tg,
  'th': flag_1_1_th,
  'tj': flag_1_1_tj,
  'tk': flag_1_1_tk,
  'tl': flag_1_1_tl,
  'tm': flag_1_1_tm,
  'tn': flag_1_1_tn,
  'to': flag_1_1_to,
  'tr': flag_1_1_tr,
  'tt': flag_1_1_tt,
  'tv': flag_1_1_tv,
  'tw': flag_1_1_tw,
  'tz': flag_1_1_tz,
  'ua': flag_1_1_ua,
  'ug': flag_1_1_ug,
  'um': flag_1_1_um,
  'un': flag_1_1_un,
  'us': flag_1_1_us,
  'uy': flag_1_1_uy,
  'uz': flag_1_1_uz,
  'va': flag_1_1_va,
  'vc': flag_1_1_vc,
  've': flag_1_1_ve,
  'vg': flag_1_1_vg,
  'vi': flag_1_1_vi,
  'vn': flag_1_1_vn,
  'vu': flag_1_1_vu,
  'wf': flag_1_1_wf,
  'ws': flag_1_1_ws,
  'xk': flag_1_1_xk,
  'xx': flag_1_1_xx,
  'ye': flag_1_1_ye,
  'yt': flag_1_1_yt,
  'za': flag_1_1_za,
  'zm': flag_1_1_zm,
  'zw': flag_1_1_zw
};

export const flags4x3: Record<string, string> = {
  'ad': flag_4_3_ad,
  'ae': flag_4_3_ae,
  'af': flag_4_3_af,
  'ag': flag_4_3_ag,
  'ai': flag_4_3_ai,
  'al': flag_4_3_al,
  'am': flag_4_3_am,
  'ao': flag_4_3_ao,
  'aq': flag_4_3_aq,
  'ar': flag_4_3_ar,
  'arab': flag_4_3_arab,
  'as': flag_4_3_as,
  'asean': flag_4_3_asean,
  'at': flag_4_3_at,
  'au': flag_4_3_au,
  'aw': flag_4_3_aw,
  'ax': flag_4_3_ax,
  'az': flag_4_3_az,
  'ba': flag_4_3_ba,
  'bb': flag_4_3_bb,
  'bd': flag_4_3_bd,
  'be': flag_4_3_be,
  'bf': flag_4_3_bf,
  'bg': flag_4_3_bg,
  'bh': flag_4_3_bh,
  'bi': flag_4_3_bi,
  'bj': flag_4_3_bj,
  'bl': flag_4_3_bl,
  'bm': flag_4_3_bm,
  'bn': flag_4_3_bn,
  'bo': flag_4_3_bo,
  'bq': flag_4_3_bq,
  'br': flag_4_3_br,
  'bs': flag_4_3_bs,
  'bt': flag_4_3_bt,
  'bv': flag_4_3_bv,
  'bw': flag_4_3_bw,
  'by': flag_4_3_by,
  'bz': flag_4_3_bz,
  'ca': flag_4_3_ca,
  'cc': flag_4_3_cc,
  'cd': flag_4_3_cd,
  'cefta': flag_4_3_cefta,
  'cf': flag_4_3_cf,
  'cg': flag_4_3_cg,
  'ch': flag_4_3_ch,
  'ci': flag_4_3_ci,
  'ck': flag_4_3_ck,
  'cl': flag_4_3_cl,
  'cm': flag_4_3_cm,
  'cn': flag_4_3_cn,
  'co': flag_4_3_co,
  'cp': flag_4_3_cp,
  'cr': flag_4_3_cr,
  'cu': flag_4_3_cu,
  'cv': flag_4_3_cv,
  'cw': flag_4_3_cw,
  'cx': flag_4_3_cx,
  'cy': flag_4_3_cy,
  'cz': flag_4_3_cz,
  'de': flag_4_3_de,
  'dg': flag_4_3_dg,
  'dj': flag_4_3_dj,
  'dk': flag_4_3_dk,
  'dm': flag_4_3_dm,
  'do': flag_4_3_do,
  'dz': flag_4_3_dz,
  'eac': flag_4_3_eac,
  'ec': flag_4_3_ec,
  'ee': flag_4_3_ee,
  'eg': flag_4_3_eg,
  'eh': flag_4_3_eh,
  'er': flag_4_3_er,
  'es-ct': flag_4_3_es_ct,
  'es-ga': flag_4_3_es_ga,
  'es-pv': flag_4_3_es_pv,
  'es': flag_4_3_es,
  'et': flag_4_3_et,
  'eu': flag_4_3_eu,
  'fi': flag_4_3_fi,
  'fj': flag_4_3_fj,
  'fk': flag_4_3_fk,
  'fm': flag_4_3_fm,
  'fo': flag_4_3_fo,
  'fr': flag_4_3_fr,
  'ga': flag_4_3_ga,
  'gb-eng': flag_4_3_gb_eng,
  'gb-nir': flag_4_3_gb_nir,
  'gb-sct': flag_4_3_gb_sct,
  'gb-wls': flag_4_3_gb_wls,
  'gb': flag_4_3_gb,
  'gd': flag_4_3_gd,
  'ge': flag_4_3_ge,
  'gf': flag_4_3_gf,
  'gg': flag_4_3_gg,
  'gh': flag_4_3_gh,
  'gi': flag_4_3_gi,
  'gl': flag_4_3_gl,
  'gm': flag_4_3_gm,
  'gn': flag_4_3_gn,
  'gp': flag_4_3_gp,
  'gq': flag_4_3_gq,
  'gr': flag_4_3_gr,
  'gs': flag_4_3_gs,
  'gt': flag_4_3_gt,
  'gu': flag_4_3_gu,
  'gw': flag_4_3_gw,
  'gy': flag_4_3_gy,
  'hk': flag_4_3_hk,
  'hm': flag_4_3_hm,
  'hn': flag_4_3_hn,
  'hr': flag_4_3_hr,
  'ht': flag_4_3_ht,
  'hu': flag_4_3_hu,
  'ic': flag_4_3_ic,
  'id': flag_4_3_id,
  'ie': flag_4_3_ie,
  'il': flag_4_3_il,
  'im': flag_4_3_im,
  'in': flag_4_3_in,
  'io': flag_4_3_io,
  'iq': flag_4_3_iq,
  'ir': flag_4_3_ir,
  'is': flag_4_3_is,
  'it': flag_4_3_it,
  'je': flag_4_3_je,
  'jm': flag_4_3_jm,
  'jo': flag_4_3_jo,
  'jp': flag_4_3_jp,
  'ke': flag_4_3_ke,
  'kg': flag_4_3_kg,
  'kh': flag_4_3_kh,
  'ki': flag_4_3_ki,
  'km': flag_4_3_km,
  'kn': flag_4_3_kn,
  'kp': flag_4_3_kp,
  'kr': flag_4_3_kr,
  'kw': flag_4_3_kw,
  'ky': flag_4_3_ky,
  'kz': flag_4_3_kz,
  'la': flag_4_3_la,
  'lb': flag_4_3_lb,
  'lc': flag_4_3_lc,
  'li': flag_4_3_li,
  'lk': flag_4_3_lk,
  'lr': flag_4_3_lr,
  'ls': flag_4_3_ls,
  'lt': flag_4_3_lt,
  'lu': flag_4_3_lu,
  'lv': flag_4_3_lv,
  'ly': flag_4_3_ly,
  'ma': flag_4_3_ma,
  'mc': flag_4_3_mc,
  'md': flag_4_3_md,
  'me': flag_4_3_me,
  'mf': flag_4_3_mf,
  'mg': flag_4_3_mg,
  'mh': flag_4_3_mh,
  'mk': flag_4_3_mk,
  'ml': flag_4_3_ml,
  'mm': flag_4_3_mm,
  'mn': flag_4_3_mn,
  'mo': flag_4_3_mo,
  'mp': flag_4_3_mp,
  'mq': flag_4_3_mq,
  'mr': flag_4_3_mr,
  'ms': flag_4_3_ms,
  'mt': flag_4_3_mt,
  'mu': flag_4_3_mu,
  'mv': flag_4_3_mv,
  'mw': flag_4_3_mw,
  'mx': flag_4_3_mx,
  'my': flag_4_3_my,
  'mz': flag_4_3_mz,
  'na': flag_4_3_na,
  'nc': flag_4_3_nc,
  'ne': flag_4_3_ne,
  'nf': flag_4_3_nf,
  'ng': flag_4_3_ng,
  'ni': flag_4_3_ni,
  'nl': flag_4_3_nl,
  'no': flag_4_3_no,
  'np': flag_4_3_np,
  'nr': flag_4_3_nr,
  'nu': flag_4_3_nu,
  'nz': flag_4_3_nz,
  'om': flag_4_3_om,
  'pa': flag_4_3_pa,
  'pc': flag_4_3_pc,
  'pe': flag_4_3_pe,
  'pf': flag_4_3_pf,
  'pg': flag_4_3_pg,
  'ph': flag_4_3_ph,
  'pk': flag_4_3_pk,
  'pl': flag_4_3_pl,
  'pm': flag_4_3_pm,
  'pn': flag_4_3_pn,
  'pr': flag_4_3_pr,
  'ps': flag_4_3_ps,
  'pt': flag_4_3_pt,
  'pw': flag_4_3_pw,
  'py': flag_4_3_py,
  'qa': flag_4_3_qa,
  're': flag_4_3_re,
  'ro': flag_4_3_ro,
  'rs': flag_4_3_rs,
  'ru': flag_4_3_ru,
  'rw': flag_4_3_rw,
  'sa': flag_4_3_sa,
  'sb': flag_4_3_sb,
  'sc': flag_4_3_sc,
  'sd': flag_4_3_sd,
  'se': flag_4_3_se,
  'sg': flag_4_3_sg,
  'sh-ac': flag_4_3_sh_ac,
  'sh-hl': flag_4_3_sh_hl,
  'sh-ta': flag_4_3_sh_ta,
  'sh': flag_4_3_sh,
  'si': flag_4_3_si,
  'sj': flag_4_3_sj,
  'sk': flag_4_3_sk,
  'sl': flag_4_3_sl,
  'sm': flag_4_3_sm,
  'sn': flag_4_3_sn,
  'so': flag_4_3_so,
  'sr': flag_4_3_sr,
  'ss': flag_4_3_ss,
  'st': flag_4_3_st,
  'sv': flag_4_3_sv,
  'sx': flag_4_3_sx,
  'sy': flag_4_3_sy,
  'sz': flag_4_3_sz,
  'tc': flag_4_3_tc,
  'td': flag_4_3_td,
  'tf': flag_4_3_tf,
  'tg': flag_4_3_tg,
  'th': flag_4_3_th,
  'tj': flag_4_3_tj,
  'tk': flag_4_3_tk,
  'tl': flag_4_3_tl,
  'tm': flag_4_3_tm,
  'tn': flag_4_3_tn,
  'to': flag_4_3_to,
  'tr': flag_4_3_tr,
  'tt': flag_4_3_tt,
  'tv': flag_4_3_tv,
  'tw': flag_4_3_tw,
  'tz': flag_4_3_tz,
  'ua': flag_4_3_ua,
  'ug': flag_4_3_ug,
  'um': flag_4_3_um,
  'un': flag_4_3_un,
  'us': flag_4_3_us,
  'uy': flag_4_3_uy,
  'uz': flag_4_3_uz,
  'va': flag_4_3_va,
  'vc': flag_4_3_vc,
  've': flag_4_3_ve,
  'vg': flag_4_3_vg,
  'vi': flag_4_3_vi,
  'vn': flag_4_3_vn,
  'vu': flag_4_3_vu,
  'wf': flag_4_3_wf,
  'ws': flag_4_3_ws,
  'xk': flag_4_3_xk,
  'xx': flag_4_3_xx,
  'ye': flag_4_3_ye,
  'yt': flag_4_3_yt,
  'za': flag_4_3_za,
  'zm': flag_4_3_zm,
  'zw': flag_4_3_zw
};
